"""initial schema

Revision ID: f9abfe8892c8
Revises: 
Create Date: 2026-09-18 15:48:43.035082
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.database.models import UTCDateTime
import sqlalchemy as sa

revision: str = 'f9abfe8892c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('pixels_per_meter', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', UTCDateTime(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('queue_at_decision', sa.Integer(), nullable=True),
    sa.Column('flow_at_decision', sa.Float(), nullable=True),
    sa.Column('predicted_flow', sa.Float(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index('ix_signal_event_time', ['signal_id', 'timestamp'], unique=False)

    op.create_table('traffic_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('bucket_start', UTCDateTime(), nullable=False),
    sa.Column('bucket_seconds', sa.Integer(), nullable=False),
    sa.Column('vehicle_count', sa.Float(), nullable=False),
    sa.Column('pedestrian_count', sa.Float(), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('crossings', sa.Integer(), nullable=False),
    sa.Column('flow_rate', sa.Float(), nullable=False),
    sa.Column('avg_dwell_seconds', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('class_breakdown', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('avg_processing_ms', sa.Float(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'bucket_start', name='uq_snapshot_camera_bucket')
    )
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_camera_time', ['camera_id', 'bucket_start'], unique=False)
        batch_op.create_index('ix_snapshot_time', ['bucket_start'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_time')
        batch_op.drop_index('ix_snapshot_camera_time')

    op.drop_table('traffic_snapshots')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_event_time')

    op.drop_table('signal_events')
    op.drop_table('cameras')
    # ### end Alembic commands ###
